name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: maven

      - name: Build with Maven
        run: mvn clean package --file pom.xml

      - name: Locate built WAR
        id: find-warp
        run: |
          echo "Looking for WAR files..."
          find target -maxdepth 1 -type f -name "*.war"
          WAR_PATH=$(find target -maxdepth 1 -type f -name "*.war" | head -n 1)
          echo "Found WAR: $WAR_PATH"
          echo "::set-output name=war::$WAR_PATH"

      - name: Deploy to Tomcat
        if: steps.find-warp.outputs.war != ''
        run: |
          WAR="${{ steps.find-warp.outputs.war }}"
          echo "Deploying WAR from path: $WAR"
          curl -v -u "${{ secrets.TOMCAT_USER }}:${{ secrets.TOMCAT_PASSWORD }}" \
               -T "$WAR" \
               "http://${{ secrets.TOMCAT_HOST }}/manager/text/deploy?path=/Ecomm&update=true"

